version: "3"

services:
  db:
    container_name: secao_06_01
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: 'senha_mysql'
    ports:
      # Garanta que não haverá conflitos de porta com um banco que esteja
      # rodando localmente
      - 3306:3306
#     networks:
#       # Conecta esse serviço com a rede que criada 
#       - store_manager_net
